Repository GSG-G9/service-seeker, pull requests merged in 2021-03, with the labels that each got.

#32 add file structure
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App/Routes/LoggedOutRoutes.js
  client/src/App/Routes/PriviteRoutes.js
  client/src/App/Routes/ProviderRoutes.js
  client/src/App/Routes/index.js
  client/src/App/index.js
  client/src/App/style.css
  client/src/Components/Button/index.js
  client/src/Components/Button/style.css
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
  client/src/Components/CardContainder/index.js
  client/src/Components/CardContainder/style.css
  client/src/Context/Authentication.js
  client/src/Pages/AboutUs/index.js
  client/src/Pages/DashboardProvider/Notifications/index.js
  client/src/Pages/DashboardProvider/Orders/index.js
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Layout/index.js
  client/src/Pages/Login/index.js
  client/src/Pages/NotFound/index.js
  client/src/Pages/Orders/index.js
  client/src/Pages/Register/index.js
  client/src/Utils/routes.constant.js
  client/src/index.css
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controller/error/404.js
  server/controller/error/500.js
  server/controller/error/index.js
  server/controller/index.js
  server/controller/provider/index.js
  server/controller/user/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.js
  server/database/queries/provider/index.js
  server/database/queries/user/index.js
  server/index.js
  server/middleware/auth/checkToken.js
  server/middleware/auth/index.js
  server/middleware/validation/index.js
  server/router/index.js
  server/router/publicRoutes.js
  server/router/user.js
  server/utils/boomify.js
  server/utils/index.js
  server/utils/jwtFunctions.js
Labels: done

#60 React Setup
  .vscode/settings.json
  client/config-overrides.js
  client/eslintrc.json
  client/lessVariables.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App/index.js
  client/src/Utils/routes.constant.js
  client/src/index.js
Labels: Priority-1, approved, awaiting-review

#63 57 setup server
  .eslintrc.json
  client/package-lock.json
  package-lock.json
  package.json
  server/app.js
  server/index.js
  server/router/index.js
  server/router/publicRoutes.js
Labels: Priority-1, back-end, done

#61 create table and insert random data
  server/database/config/build.sql
  server/database/config/fakeData.js
  server/database/config/fakeData.sql
Labels: Priority-1, awaiting-review, request-change

#72 71 protect middleware
  .eslintrc.json
  package-lock.json
  package.json
  server/middleware/auth/checkToken.js
  server/middleware/auth/index.js
  server/middleware/auth/providerProtected.js
  server/utils/boomify.js
  server/utils/index.js
  server/utils/jwtFunctions.js
Labels: Priority-1, awaiting-review, back-end

#76 75 server client error
  server/app.js
  server/controller/error/404.js
  server/controller/error/500.js
  server/controller/error/index.js
  server/controller/index.js
Labels: Priority-1, awaiting-review, back-end

#67 POST /login Route Backend
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/user/index.js
  server/controller/user/login.js
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/user/checkUserByEmail.js
  server/database/queries/user/index.js
  server/middleware/validation/index.js
  server/middleware/validation/login.js
  server/router/index.js
  server/router/publicRoutes.js
Labels: approved, awaiting-review, back-end

#78 create input component common
  client/src/Components/Input/index.js
  client/src/Components/Input/style.css
Labels: awaiting-review

#70 create button component as common component
  client/package.json
  client/src/Components/Button/index.js
  client/src/Components/Button/style.css
  client/src/Components/Input/index.js
Labels: awaiting-review

#85 Avatar component
  .gitignore
  client/package.json
  client/src/Components/Avatar/index.js
Labels: Priority-1, awaiting-review, front-end

#86 logout user
  server/controller/index.js
  server/controller/user/index.js
  server/controller/user/logout.js
  server/router/publicRoutes.js
Labels: awaiting-review, back-end

#66 GET /is-auth Route Backend
  .eslintrc.json
  package.json
  server/app.js
  server/controller/error/index.js
  server/controller/index.js
  server/controller/user/index.js
  server/controller/user/isAuth.js
  server/controller/user/login.js
  server/database/config/databaseConfig.sql
  server/database/queries/user/getUserData.js
  server/database/queries/user/index.js
  server/middleware/auth/checkToken.js
  server/middleware/auth/index.js
  server/middleware/validation/login.js
  server/router/index.js
  server/router/user.js
  server/utils/index.js
Labels: Priority-1, approved, back-end

#65 Private Routes Components
  client/.eslintrc.json
  client/src/App/Routes/LoggedOutRoutes.js
  client/src/App/Routes/PrivateRoutes.js
  client/src/App/Routes/PriviteRoutes.js
  client/src/App/Routes/ProviderRoutes.js
  client/src/App/Routes/index.js
  client/src/App/index.js
  client/src/Context/Authentication.js
Labels: Priority-1, awaiting-review, front-end
