Repository GSG-G9/service-seeker, pull requests merged in 2021-04, with the labels that each got.

#97 card and button component style
  client/src/Components/Button/style.css
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
Labels: awaiting-review, front-end

#100 Update Providers Table
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/provider/getAllProvider.js
Labels: approved, awaiting-review, back-end

#94 search/filter component
  client/src/Components/Search/index.js
  client/src/Components/Search/style.css
  client/src/Components/Select/index.js
  client/src/Utils/data.js
Labels: approved, awaiting-review, front-end

#96 Card Container Component
  client/.eslintrc.json
  client/lessVariables.js
  client/src/Components/Avatar/index.js
  client/src/Components/Button/style.css
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
  client/src/Components/CardContainder/index.js
  client/src/Components/CardContainder/style.css
  client/src/Components/CardContainer/index.js
  client/src/Components/CardContainer/style.css
Labels: awaiting-review, front-end

#93 34 signup page
  client/src/App/index.js
  client/src/Components/Select/index.js
  client/src/Pages/Register/index.js
  client/src/Pages/Register/style.css
  client/src/Utils/assets/images/signupBg.svg
Labels: Priority-1, front-end, request-change

#77 73 layout page
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/Components/Button/style.css
  client/src/Components/CardContainer/index.js
  client/src/Components/Footer/index.js
  client/src/Components/Footer/style.css
  client/src/Components/NavBar/index.js
  client/src/Components/NavBar/style.css
  client/src/Components/Select/index.js
  client/src/Components/UserInfo/index.js
  client/src/Components/UserInfo/style.css
  client/src/Context/Authentication.js
  client/src/Pages/Layout/index.js
  client/src/Pages/Layout/style.css
  client/src/Pages/Login/index.js
  client/src/Pages/Login/style.css
  client/src/Pages/Register/index.js
  client/src/Utils/assets/images/footer.svg
  client/src/Utils/assets/images/login.svg
  client/src/Utils/errorHandel.js
  package-lock.json
  server/middleware/auth/checkToken.js
Labels: Priority-1, awaiting-review, front-end

#99 create landing page
  client/src/App/index.js
  client/src/Components/Button/style.css
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
  client/src/Components/CardContainer/index.js
  client/src/Components/Footer/style.css
  client/src/Components/Search/index.js
  client/src/Components/Search/style.css
  client/src/Components/Select/index.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Landing/style.css
  client/src/Pages/Layout/style.css
  client/src/Utils/data.js
  server/database/config/fakeData.sql
  server/database/queries/provider/getAllProvider.js
Labels: awaiting-review, front-end

#109 GET /user/order-requests Route
  server/controller/index.js
  server/controller/user/getUserOrdersReq.js
  server/controller/user/index.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/getUserOrdersReq.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: awaiting-review, back-end

#113 GET /user/orders Route
  server/controller/index.js
  server/controller/user/getUserOrders.js
  server/controller/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/getUserOrders.js
  server/database/queries/user/getUserOrdersReq.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: awaiting-review, back-end

#98 47 user order request
  server/controller/index.js
  server/controller/user/addOrderRequest.js
  server/controller/user/index.js
  server/database/queries/index.js
  server/database/queries/user/addOrderRequest.js
  server/database/queries/user/getUserOrdersReq.js
  server/database/queries/user/index.js
  server/middleware/validation/index.js
  server/middleware/validation/orderRequest.js
  server/router/user.js
Labels: awaiting-review, back-end

#106 delete order route
  server/controller/index.js
  server/controller/user/deleteOrderRequest.js
  server/controller/user/index.js
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/deleteOrderReq.js
  server/database/queries/user/index.js
  server/router/user.js
Labels: awaiting-review, back-end

#115 Table component
  client/src/Components/Table/Columns/index.js
  client/src/Components/Table/index.js
  client/src/Components/Table/style.css
Labels: awaiting-review, front-end

#108 Get order requests related to the providers.
  server/controller/index.js
  server/controller/provider/getPendingOrderRequest.js
  server/controller/provider/index.js
  server/controller/user/addOrderRequest.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/provider/getPendingOrderRequest.js
  server/database/queries/provider/index.js
  server/router/index.js
  server/router/provider.js
Labels: back-end, request-change

#112 create layout providers
  client/package-lock.json
  client/src/App/index.js
  client/src/Components/Avatar/index.js
  client/src/Components/Logout/index.js
  client/src/Components/UserInfo/index.js
  client/src/Pages/DashboardProvider/Notifications/index.js
  client/src/Pages/DashboardProvider/Orders/index.js
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  package-lock.json
Labels: awaiting-review, front-end

#122 get accepted order
  server/controller/index.js
  server/controller/provider/getAcceptedOrders.js
  server/controller/provider/index.js
  server/database/queries/index.js
  server/database/queries/provider/getAcceptOrders.js
  server/database/queries/provider/index.js
  server/router/provider.js
Labels: back-end, request-change

#104 Order request component
  client/public/static/avatar.png
  client/public/static/order-bg.png
  client/src/Components/Card/index.js
  client/src/Components/CardContainer/index.js
  client/src/Components/UserModal/index.js
  client/src/Components/UserModal/style.css
  client/src/Pages/Landing/HireMeModal/index.js
  client/src/Pages/Landing/HireMeModal/style.css
  client/src/Pages/Landing/index.js
  client/src/Pages/Orders/style.css
Labels: awaiting-review, front-end

#123 create qurey and route for availablity #119
  server/controller/index.js
  server/controller/provider/index.js
  server/controller/provider/updateAvailability.js
  server/database/queries/provider/index.js
  server/database/queries/provider/updateِِِAvailabilityQuery.js
  server/router/provider.js
Labels: awaiting-review, back-end

#129 create qurey to get provider data and end function of switch
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  server/controller/index.js
  server/controller/provider/getProviderData.js
  server/controller/provider/index.js
  server/controller/provider/updateAvailability.js
  server/database/queries/index.js
  server/database/queries/provider/getProviderById.js
  server/database/queries/provider/index.js
  server/database/queries/provider/updateِِِAvailabilityQuery.js
  server/router/provider.js
Labels: back-end, request-change

#125 Add service type
  client/src/Components/Card/index.js
  client/src/Components/Card/style.css
  client/src/Components/UserModal/index.js
  client/src/Components/UserModal/style.css
  client/src/Pages/Landing/index.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/provider/getAllProvider.js
  server/database/queries/user/getUserOrders.js
  server/database/queries/user/getUserOrdersReq.js
Labels: awaiting-review

#124 Order requests provider table
  client/src/Components/Table/Columns/index.js
  client/src/Components/Table/Columns/providerOrderPending.js
  client/src/Components/Table/index.js
  client/src/Pages/DashboardProvider/Orders/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/DashboardProvider/Orders/style.css
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/Layout/style.css
  server/database/queries/provider/getPendingOrderRequest.js
Labels: Priority-1, front-end, request-change

#130 Fix Orders Request
  server/controller/user/addOrderRequest.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/user/getUserOrders.js
  server/database/queries/user/getUserOrdersReq.js
  server/database/queries/user/index.js
  server/database/queries/user/isAlreadyHeired.js
Labels: awaiting-review

#126 Order Page
  client/src/App/index.js
  client/src/Components/Button/style.css
  client/src/Components/Table/Columns/UserOrder.js
  client/src/Components/Table/Columns/UserOrderReq.js
  client/src/Components/Table/Columns/index.js
  client/src/Components/UserModal/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Orders/OrdersReqTab/OrdersReqModal/index.js
  client/src/Pages/Orders/OrdersReqTab/OrdersReqModal/style.css
  client/src/Pages/Orders/OrdersReqTab/index.js
  client/src/Pages/Orders/OrdersReqTab/style.css
  client/src/Pages/Orders/OrdersTab/OrdersModal/index.js
  client/src/Pages/Orders/OrdersTab/index.js
  client/src/Pages/Orders/OrdersTab/style.css
  client/src/Pages/Orders/index.js
  client/src/Pages/Orders/style.css
  client/src/Pages/index.js
  client/src/Utils/getStatusColor.js
Labels: awaiting-review, front-end

#128 create qury for update profile provider
  server/controller/index.js
  server/controller/provider/index.js
  server/controller/provider/updateProvider.js
  server/database/queries/index.js
  server/database/queries/provider/index.js
  server/database/queries/provider/updateProvider.js
  server/middleware/validation/index.js
  server/middleware/validation/profileUpdateValidation.js
  server/router/provider.js
Labels: awaiting-review, back-end

#138 Fix hire Me Btn
  client/src/Components/Card/index.js
  client/src/Pages/Landing/index.js
Labels: front-end

#140 GET/user/notifications Route
  server/controller/index.js
  server/controller/orders/addOrderRequest.js
  server/controller/orders/deleteOrderRequest.js
  server/controller/user/getUserNotifications.js
  server/controller/user/index.js
  server/database/queries/index.js
  server/database/queries/order/index.js
  server/database/queries/user/addUserNotification.js
  server/database/queries/user/getUserNotifications.js
  server/database/queries/user/index.js
  server/router/provider.js
  server/router/user.js
  server/utils/index.js
  server/utils/sendNotification.js
Labels: awaiting-review, back-end

#131 accepted orders dashboard
  client/package-lock.json
  client/src/Components/Table/Columns/index.js
  client/src/Components/Table/Columns/providerAcceptedOrders.js
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/index.js
  client/src/Pages/DashboardProvider/Orders/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/Landing/HireMeModal/index.js
  client/src/Utils/getStatusColor.js
  server/database/queries/order/getAcceptOrders.js
Labels: awaiting-review, front-end

#134 Accept order
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/acceptModal.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/style.css
  server/database/config/fakeData.sql
Labels: awaiting-review, front-end

#145 Not Found Page
  client/src/App/index.js
  client/src/Pages/NotFound/index.js
  client/src/Pages/NotFound/style.css
  client/src/Pages/index.js
  client/src/Utils/assets/images/NotFoundText.svg
Labels: awaiting-review

#133 create profile file
  client/src/Components/Select/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/DashboardProvider/Profile/style.css
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Register/style.css
  server/controller/provider/updateProvider.js
  server/controller/user/isAuth.js
  server/database/queries/provider/updateProvider.js
  server/middleware/validation/profileUpdateValidation.js
Labels: front-end, in Progress

#144 About us page
  client/src/App/index.js
  client/src/Pages/AboutUs/index.js
  client/src/Pages/AboutUs/style.css
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Landing/style.css
  client/src/Pages/Layout/style.css
  client/src/Pages/Login/style.css
  client/src/Pages/Orders/OrdersReqTab/OrdersReqModal/style.css
  client/src/Pages/Orders/OrdersReqTab/style.css
  client/src/Pages/Orders/style.css
  client/src/Pages/Register/style.css
  client/src/Pages/index.js
  client/src/Utils/assets/images/AboutUs.svg
Labels: awaiting-review

#137 Patch /provider/orders/:orderId Router
  .eslintrc.json
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/orders/index.js
  server/controller/orders/updateOrderState.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/index.js
  server/database/queries/order/getOrderReqByOrderId.js
  server/database/queries/order/index.js
  server/database/queries/order/updateOrders/index.js
  server/database/queries/order/updateOrders/updateFinish.js
  server/database/queries/order/updateOrders/updatePause.js
  server/database/queries/order/updateOrders/updateStart.js
  server/database/queries/provider/getPriceHourProvider.js
  server/database/queries/provider/getProviderById.js
  server/database/queries/provider/index.js
  server/middleware/validation/index.js
  server/middleware/validation/updateOrderState.js
  server/router/provider.js
  server/utils/calculateDuration.js
  server/utils/index.js
Labels: awaiting-review, back-end

#142 Start and pause work popup
  client/src/Components/Button/style.css
  client/src/Components/WorkStatusModal/index.js
  client/src/Components/WorkStatusModal/style.css
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/StartWorkModal/StateBtn/index.js
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/StartWorkModal/index.js
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/StartWorkModal/style.css
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/AcceptModal/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/AcceptModal/style.css
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Utils/getStatusColor.js
  server/controller/orders/updateOrderState.js
  server/database/queries/index.js
  server/database/queries/order/getAcceptOrders.js
Labels: Priority-1, front-end, in Progress

#159 fake data
  client/src/Utils/data.js
  server/database/config/fakeData.sql
Labels: awaiting-review

#166 messsage fix
  client/src/Components/Logout/index.js
  client/src/Components/NotificationPanel/index.js
  client/src/Pages/DashboardProvider/Notifications/NotificationsTable/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/Landing/HireMeModal/index.js
  client/src/Pages/Landing/index.js
  client/src/Pages/Orders/OrdersReqTab/index.js
  client/src/Pages/Orders/OrdersTab/index.js
  server/database/config/fakeData.sql
Labels: awaiting-review

#169 Add See More on Tables
  client/src/Components/Table/Columns/UserOrder.js
  client/src/Components/Table/Columns/UserOrderReq.js
  client/src/Components/Table/Columns/index.js
  client/src/Components/Table/Columns/providerAcceptedOrders.js
  client/src/Components/Table/Columns/providerOrderPending.js
  client/src/Components/UserModal/style.css
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/index.js
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/index.js
  client/src/Pages/Orders/OrdersReqTab/index.js
  client/src/Pages/Orders/OrdersTab/index.js
Labels: awaiting-review

#171 Rename Change
  client/src/Components/NavBar/index.js
  client/src/Components/NavBar/style.css
  client/src/Pages/AboutUs/index.js
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Login/index.js
  client/src/Pages/Login/style.css
Labels: awaiting-review

#177 Fix Notification Menu
  client/src/Components/NotificationPanel/index.js
  client/src/Components/NotificationPanel/style.css
  client/src/Components/UserInfo/index.js
  client/src/Components/UserInfo/style.css
Labels: awaiting-review

#167 send the bill through email
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/StartWorkModal/index.js
  package-lock.json
  package.json
  server/controller/orders/updateOrderState.js
  server/database/queries/order/getOrderReqByOrderId.js
  server/utils/index.js
  server/utils/sendBill.js
Labels: back-end, request-change

#180 Sort Orders by descending
  server/controller/orders/getAcceptedOrders.js
  server/controller/orders/getUserOrdersReq.js
  server/database/queries/order/getAcceptOrders.js
  server/database/queries/order/getOrderReqByOrderId.js
  server/database/queries/order/getPendingOrderRequest.js
  server/database/queries/user/getUserNotifications.js
  server/database/queries/user/getUserOrders.js
  server/database/queries/user/getUserOrdersReq.js
Labels: awaiting-review, fix-bug

#184 Fix Style
  client/src/Components/Button/style.css
  client/src/Components/Card/style.css
  client/src/Components/Footer/style.css
  client/src/Components/Input/index.js
  client/src/Components/Search/style.css
  client/src/Components/Table/style.css
  client/src/Components/UserModal/style.css
  client/src/Components/WorkStatusModal/style.css
  client/src/Pages/DashboardProvider/Notifications/style.css
  client/src/Pages/DashboardProvider/Orders/acceptedOrders/StartWorkModal/style.css
  client/src/Pages/DashboardProvider/Orders/pendingOrderRequest/AcceptModal/style.css
  client/src/Pages/DashboardProvider/Orders/style.css
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/DashboardProvider/Profile/style.css
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Landing/HireMeModal/style.css
  client/src/Pages/Login/index.js
  client/src/Pages/Login/style.css
  client/src/Pages/Register/index.js
  client/src/Pages/Register/style.css
  client/src/index.css
Labels: awaiting-review

#176 More Info Component
  client/src/Components/MoreInfo/index.js
  client/src/Components/MoreInfo/style.css
  client/src/Pages/DashboardProvider/Orders/index.js
  client/src/Pages/DashboardProvider/Orders/style.css
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Login/index.js
  client/src/Pages/Orders/index.js
  client/src/Pages/Orders/style.css
  client/src/Utils/moreInfo.constant.js
  server/database/config/fakeData.sql
Labels: awaiting-review

#186 Handling update order state notification
  server/controller/orders/postOrder.js
  server/controller/orders/updateOrderState.js
  server/database/queries/order/updateStateOrderReq.js
  server/utils/sendNotification.js
Labels: awaiting-review

#143 Image uploder
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/DashboardProvider/Profile/style.css
  client/src/Pages/DashboardProvider/Profile/uploadImage.js
  client/src/Pages/DashboardProvider/index.js
  client/src/Pages/DashboardProvider/style.css
  client/src/Pages/Landing/index.js
  package-lock.json
  package.json
  server/app.js
  server/controller/index.js
  server/controller/provider/index.js
  server/controller/provider/updateCoverImageCon.js
  server/database/queries/index.js
  server/database/queries/provider/index.js
  server/database/queries/provider/updateCoverImageQuery.js
  server/database/queries/provider/updateProvider.js
  server/middleware/validation/updateCoverImage.js
  server/middleware/validation/updateProviderValidation.js
  server/router/provider.js
  server/utils/index.js
  server/utils/uploadCloudinary.js
Labels: Priority-2, awaiting-review, back-end, front-end

#172 fix validation
  client/src/Pages/DashboardProvider/Profile/index.js
  client/src/Pages/Register/index.js
Labels: fix-bug, front-end
